# File: nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-openresty-service
spec:
  selector:
    app: nginx-openresty
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort  # Exposes the service on a port on each node in the cluster
